GET http://localhost:3000/api/ping

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "michelle13@test.com",
    "username": "michelle123",
    "password": "password123"
}