import { ROLES, Role } from "./roles";
import { PERMISSIONS, Permission } from "./permissions";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.ADMIN]: [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_USERS,
  ],
  [ROLES.COORDINATOR]: [
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_USERS,
  ],
  [ROLES.BORROWER]: [PERMISSIONS.VIEW_REPORTS],
  [ROLES.VIEWER]: [PERMISSIONS.VIEW_REPORTS],
};
