import { ROLES, Role } from "./roles";
import { PERMISSIONS, Permission } from "./permissions";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPERADMIN]: [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.PATCH_USER,
    PERMISSIONS.VIEW_USER,
    PERMISSIONS.VIEW_ONE_USER,
    PERMISSIONS.PATCH_USER_ROLE,
    PERMISSIONS.VIEW_ROLE_PERMISSIONS,
    PERMISSIONS.PATCH_ROLE_PERMISSIONS,
    PERMISSIONS.GRANT_USER_PERMISSIONS,
    PERMISSIONS.DENY_USER_PERMISSIONS,
    PERMISSIONS.VIEW_USER_ROLE_PERMISSIONS,
  ],
  [ROLES.TECHNICAL]: [
    PERMISSIONS.PATCH_USER,
    PERMISSIONS.VIEW_USER,
    PERMISSIONS.VIEW_ONE_USER,
    PERMISSIONS.PATCH_USER_ROLE,
    PERMISSIONS.VIEW_ROLE_PERMISSIONS,
    PERMISSIONS.PATCH_ROLE_PERMISSIONS,
    PERMISSIONS.VIEW_USER_ROLE_PERMISSIONS,
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.PATCH_USER,
    PERMISSIONS.VIEW_USER,
    PERMISSIONS.VIEW_ONE_USER,
    PERMISSIONS.PATCH_USER_ROLE,
    PERMISSIONS.VIEW_ROLE_PERMISSIONS,
    PERMISSIONS.PATCH_ROLE_PERMISSIONS,
    PERMISSIONS.GRANT_USER_PERMISSIONS,
    PERMISSIONS.DENY_USER_PERMISSIONS,
    PERMISSIONS.VIEW_USER_ROLE_PERMISSIONS,
  ],
  [ROLES.COORDINATOR]: [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.PATCH_USER,
    PERMISSIONS.VIEW_USER,
    PERMISSIONS.VIEW_ONE_USER,
    PERMISSIONS.GRANT_USER_PERMISSIONS,
    PERMISSIONS.DENY_USER_PERMISSIONS,
    PERMISSIONS.VIEW_USER_ROLE_PERMISSIONS,
  ],
  [ROLES.BORROWER]: [
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.VIEW_USER,
    PERMISSIONS.VIEW_ONE_USER,
    PERMISSIONS.VIEW_ROLE_PERMISSIONS,
    PERMISSIONS.VIEW_USER_ROLE_PERMISSIONS,
  ],
};
